apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: centauri-app
  labels:
    name: centauri
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: centauri-app
    spec:
      containers:
      - name: centauri
        image: centauri
        ports:
          - containerPort: 5000

        readinessProbe:
          httpGet:
            path: /ping
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /ping
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
