apiVersion: v1
kind: Service
metadata:
  name: centauri
  labels:
    service: centauri
spec:
  type: NodePort
  selector:
    app: centauri-app
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: centauri-tcp
