apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nestor-ingress

spec:
  rules:
  - http:
      paths:
        - path: /proxima
          backend:
            serviceName: proxima
            servicePort: proxima-tcp
