apiVersion: v1
kind: Service
metadata:
  name: proxima
  labels:
    service: proxima
spec:
  type: NodePort
  selector:
    app: proxima
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: proxima-tcp
